CREATE TABLE IF NOT EXISTS schema_migrations(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  version CHAR(23) NOT NULL,
  name VARCHAR(255) NOT NULL,
  up TEXT NOT NULL,
  down TEXT NOT NULL,
  run_at DATETIME
);

ALTER TABLE schema_migrations ADD UNIQUE INDEX (version, name);
