CREATE TABLE settings(
  id BIGINT NOT NULL AUTO_INCREMENT,,
  key VARCHAR(255) NOT NULL,
  value BLOB NOT NULL,
  salt BLOB,
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_settings_key ON settings(key);
